name: encrypted_password_checker
description: A Dart CLI application to check encrypted passwords
version: 1.0.0
environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  bcrypt: ^1.1.3

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
